apiVersion: v1
kind: Service
metadata:
  name: jobradar-tracker-api
  namespace: jobradar
spec:
  selector:
    app: tracker-api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
