apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: ""
namespace: jobradar-staging

bases:
  - ../../base

patches:
  # In staging, run only 1 replica to save resources
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: jobradar-tracker-api
  # Override the namespace for all resources
  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: jobradar-staging
    target:
      kind: Namespace
      name: jobradar
